"""add budget model"


Revision ID: 62556d9b8811
Revises: 763b6aad8818
Create Date: 2023-09-11 02:19:00.153443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62556d9b8811'
down_revision = '763b6aad8818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('income', sa.Integer(), nullable=False),
    sa.Column('expense', sa.Integer(), nullable=False),
    sa.Column('person', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget')
    # ### end Alembic commands ###
